import { AuthController } from '@controllers/auth/auth.controller';
import { AddressController } from '@controllers/address/address.controller';
import { CompanyController } from '@controllers/company/company.controller';
import { AddressRepository } from '@repositories/address/address.repository';
import { AuthRepository } from '@repositories/auth/auth.repository';
import { CompanyRepository } from '@repositories/company/company.respository';
import { EmailSender } from '@services/email.service';
import { container } from 'tsyringe';
import { ApiResponse } from '@utils/api-response';
import { JwtHandler } from '@services/jwt.service';
import { TaskTypeRepository } from '@repositories/task/task-type.repository';
import { TaskTypeController } from '@controllers/task/task-type.controller';
import { CompanyFakeController } from '@controllers/company/company-fake.controller';
import { EmployeePositionController } from '@controllers/employee/employee-position.controller';
import { EmployeePositionRepository } from '@repositories/employee/employee-position.repository';
import { DepartmentRepository } from '@repositories/department/department.repository';
import { DepartmentController } from '@controllers/department/department.controller';
import { ProductionLineController } from '@controllers/production-line/production-line.controller';
import { ProductionLineRepository } from '@repositories/production-line/production-line.repository';
import { EmployeeRepository } from '@repositories/employee/employee.repository';
import { EmployeeController } from '@controllers/employee/employee.controller';
import { CloudStorage } from 'GCP/cloud-storage.gcp';
import { TaskRepository } from '@repositories/task/task.repository';
import { TaskController } from '@controllers/task/task.controller';
import { ProductTypeController } from '@controllers/product/product-types.controller';
import { ProductTypeRepository } from '@repositories/product/product-type.repository';
import { ProductRepository } from '@repositories/product/product.repository';
import { ProductController } from '@controllers/product/product.controller';
import { UnitController } from '@controllers/unit/unit.controller';
import { UnitRepository } from '@repositories/unit/unit.repository';

container.registerSingleton('AuthRepository', AuthRepository);
container.registerSingleton('AuthController', AuthController);
container.registerSingleton('CompanyRepository', CompanyRepository);
container.registerSingleton('CompanyController', CompanyController);
container.registerSingleton('CompanyFakeController', CompanyFakeController);
container.registerSingleton('AddressRepository', AddressRepository);
container.registerSingleton('AddressController', AddressController);
container.registerSingleton('EmployeeController', EmployeeController);
container.registerSingleton('EmployeeRepository', EmployeeRepository);
container.registerSingleton('EmployeePositionController', EmployeePositionController);
container.registerSingleton('EmployeePositionRepository', EmployeePositionRepository);
container.registerSingleton('TaskRepository', TaskRepository);
container.registerSingleton('TaskController', TaskController);
container.registerSingleton('TaskTypeRepository', TaskTypeRepository);
container.registerSingleton('TaskTypeController', TaskTypeController);
container.registerSingleton('DepartmentRepository', DepartmentRepository);
container.registerSingleton('DepartmentController', DepartmentController);
container.registerSingleton('ProductionLineController', ProductionLineController);
container.registerSingleton('ProductionLineRepository', ProductionLineRepository);
container.registerSingleton('ProductTypeController', ProductTypeController);
container.registerSingleton('ProductTypeRepository', ProductTypeRepository);
container.registerSingleton('ProductController', ProductController);
container.registerSingleton('ProductRepository', ProductRepository);
container.registerSingleton('UnitController', UnitController);
container.registerSingleton('UnitRepository', UnitRepository);
container.registerSingleton('JwtHandler', JwtHandler);
container.registerSingleton('EmailSender', EmailSender);
container.registerSingleton('ApiResponse', ApiResponse);
container.registerSingleton('CloudStorage', CloudStorage);
