export const TOKENS = {
  AuthRepository: Symbol.for('AuthRepository'),
  AuthBaseRepository: Symbol.for('AuthBaseRepository'),
  AuthController: Symbol.for('AuthController'),
  // UnitRepository: Symbol.for('UnitRepository'),
  UnitBaseRepository: Symbol.for('UnitBaseRepository'),
  UnitController: Symbol.for('UnitController'),
  CompanyRepository: Symbol.for('CompanyRepository'),
  CompanyBaseRepository: Symbol.for('CompanyBaseRepository'),
  CompanyController: Symbol.for('CompanyController'),
  CompanyFakeController: Symbol.for('CompanyFakeController'),
  // AddressRepository: Symbol.for('AddressRepository'),
  AddressBaseRepository: Symbol.for('AddressBaseRepository'),
  AddressController: Symbol.for('AddressController'),
  EmployeeRepository: Symbol.for('EmployeeRepository'),
  EmployeeBaseRepository: Symbol.for('EmployeeBaseRepository'),
  EmployeeController: Symbol.for('EmployeeController'),
  EmployeePositionBaseRepository: Symbol.for('EmployeePositionBaseRepository'),
  EmployeePositionController: Symbol.for('EmployeePositionController'),
  TaskRepository: Symbol.for('TaskRepository'),
  TaskBaseRepository: Symbol.for('TaskBaseRepository'),
  TaskController: Symbol.for('TaskController'),
  // TaskTypeRepository: Symbol.for('TaskTypeRepository'),
  TaskTypeBaseRepository: Symbol.for('TaskTypeBaseRepository'),
  TaskTypeController: Symbol.for('TaskTypeController'),
  // DepartmentRepository: Symbol.for('DepartmentRepository'),
  DepartmentBaseRepository: Symbol.for('DepartmentBaseRepository'),
  DepartmentController: Symbol.for('DepartmentController'),
  // ProductionLineRepository: Symbol.for('ProductionLineRepository'),
  ProductionLineBaseRepository: Symbol.for('ProductionLineBaseRepository'),
  ProductionLineController: Symbol.for('ProductionLineController'),
  // ProductTypeRepository: Symbol.for('ProductTypeRepository'),
  ProductTypeBaseRepository: Symbol.for('ProductTypeBaseRepository'),
  ProductTypeController: Symbol.for('ProductTypeController'),
  ProductRepository: Symbol.for('ProductRepository'),
  ProductBaseRepository: Symbol.for('ProductBaseRepository'),
  ProductController: Symbol.for('ProductController'),
  JwtHandler: Symbol.for('JwtHandler'),
  EmailSender: Symbol.for('EmailSender'),
  ApiResponse: Symbol.for('ApiResponse'),
  CloudStorage: Symbol.for('CloudStorage'),
};
