import { Router } from 'express';
import { authRoute } from './auth/auth.route';
import { companyRoute } from './company/company.route';
import { addressRoute } from './address/address.route';
import { departmentRoute } from './department/department.route';
import { companyFakeRoute } from './company/company.fake.route';
import { employeePositionRoute } from './employee/employee-position.route';
import { taskTypeRoute } from './task/task-type.route';
import { productionLineRoute } from './production-line/production-line.route';
import { employeeRoute } from './employee/employee.route';
import { taskRoute } from './task/task.route';
import { productTypeRoute } from './product/product-type.route';
import { productRoute } from './product/product.route';
import { unitRoute } from './unit/unit.route';
import { taskFakeRoute } from './task/task-fake.route';

const router = Router();
router.use(authRoute);
router.use(companyRoute);
router.use(companyFakeRoute);
router.use(addressRoute);
router.use(employeeRoute);
router.use(employeePositionRoute);
router.use(taskRoute);
router.use(taskFakeRoute);
router.use(taskTypeRoute);
router.use(departmentRoute);
router.use(productionLineRoute);
router.use(productTypeRoute);
router.use(productRoute);
router.use(unitRoute);

export { router };
